name: Base image for TEI Publisher application packages

on:
  push:
    # Publish `main` as Docker `:latest` image.
    branches:
      - main
      - "release/*"

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  pull_request:
    branches: [main]

  workflow_dispatch:

env:
  IMAGE_NAME: jinntec/tp-base
  REGISTRY: ghcr.io
  TEST_TAG: exist-ci

jobs:
  build:
    name: Build and Test Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        EXIST_BASE: [dev6-nonroot-j8, release-nonroot, latest]
    # NOTE (DP): Test on PRs and pushes
    if: github.ref == 'refs/heads/main' || github.base_ref ==  'main'
    steps:
      # SETUP
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Make buildkit default
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true

      - name: Install bats
        # run: sudo apt-get install bats libsaxonb-java
        run: sudo apt-get install bats libsaxonb-java

      - name: Check local images
        run: docker image ls

      # TODO(DP) needs adjusting for multi-stage see #5
      - name: Modify config files
        run: saxonb-xslt -s:dump/exist-distribution-${{ env.EXIST_VER }}/etc/log4j2.xml -xsl:log4j2-docker.xslt -o:log4j2.xml

      # BUILD
      - name: Build default images for testing on CI
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: ${{ env.TEST_TAG }}

  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Make buildkit default
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # TODO(DP): This could be extended further
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      # was ${{ github.actor }}
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            ${{ EXIST_BASE }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
