name: Base image for TEI Publisher application packages

on:
  push:
    # Publish `main` as Docker `:latest` image.
    branches:
      - main
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  pull_request:
    branches: [main]
  schedule:
    - cron: "11 */8 * * *"

  workflow_dispatch:

env:
  IMAGE_NAME: jinntec/base
  REGISTRY: ghcr.io
  TEST_TAG: exist-ci

jobs:
  build:
    name: Build and Test Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        EXIST_BASE: [6.2.0, release, latest]
    # NOTE (DP): Test on PRs and pushes
    if: github.ref == 'refs/heads/main' || github.base_ref ==  'main'
    steps:
      # SETUP
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Make buildkit default
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true

      - name: Install bats
        run: sudo apt-get install bats

      - name: Check local images
        run: docker image ls

      # BUILD
      - name: Build default images for testing on CI
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            EXIST_BASE=${{ matrix.EXIST_BASE }}
          load: true
          tags: ${{ env.TEST_TAG }}
          # cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache

      # TEST
      - name: Start exist-ci containers
        run: |
          docker run -dit -p 8080:8080 --name exist --rm ${{ env.TEST_TAG }}
          sleep 35s

      - name: Run tests
        run: bats --tap test/*.bats

  push:
    # Ensure test job passes before pushing image.
    needs: build

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Make buildkit default
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # TODO(DP): This could be extended further
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      # was ${{ github.actor }}
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/tags/v*'
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            EXIST_BASE=release
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          sbom: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          # cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max
